# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(name)s ; %(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# File Storage
FILE_STORAGE_URL: "http://file-storage:80/files/"

# FINGERPRINTER
FLOW_DIRECTORY: "/opt/DicomFlow/flows"
SUB_QUEUE_KWARGS:
  queue: ""
  passive: False
  durable: False
  exclusive: False
  auto_delete: True
SUB_PREFETCH_COUNT: 1
SUB_MODELS:
  - exchange: "storescp"
    exchange_type: "topic"
    routing_keys: ["success"]
    routing_key_fetch_echo: "fetch"

PUB_MODELS:
  - exchange: "fingerprinter"
    exchange_type: "topic"


