# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_DIR: "/opt/RadDeploy/file_storage/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(name)s ; %(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# File Storage
FILE_STORAGE_SUFFIX: ".tar"
FILE_STORAGE_TEMP_DIR: "/opt/RadDeploy/file_storage/files"
FILE_STORAGE_STATIC_DIR: "/opt/RadDeploy/file_sotrage/static"
FILE_STORAGE_HOST: "file-storage"
FILE_STORAGE_PORT: 80

# File Janitor
FILE_JANITOR_DELETE_FILES_AFTER: 43200  # 12 hours
FILE_JANITOR_RUN_INTERVAL: 1800 # 30 minutes