# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_DIR: "/opt/RadDeploy/scheduler/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(name)s ; %(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

SUB_QUEUE_KWARGS:
  queue: ""
  passive: False
  durable: False
  exclusive: False
  auto_delete: True

SUB_PREFETCH_COUNT: 1
SCHEDULER_FLOW_INCOMING_EXCHANGES: ["fingerprinter"]
SCHEDULER_JOB_INCOMING_EXCHANGES: ["consumer"]
SCHEDULER_RESCHEDULE_PRIORITY: 5
SCHEDULER_DATABASE_PATH: "/opt/RadDeploy/scheduler/database.db"
SUB_MODELS:
  - exchange: "fingerprinter"
    exchange_type: "topic"
    routing_keys: ["success"]
    routing_key_fetch_echo: "fetch"

  - exchange: "consumer"
    exchange_type: "topic"
    routing_keys: ["success", "error", "fail"]
    routing_key_fetch_echo: "fetch"

PUB_MODELS:
  - exchange: "scheduler"
    exchange_type: "topic"
    routing_key_values:
      GPU: "gpu"
      CPU: "cpu"