name: "test"
triggers:
  - Modality: ["MR"]
    SeriesDescription: ["3D", '(?i)tra']
  - Modality: ["CT"]
models:
  - docker_kwargs:
      image: busybox
      command: sh -c 'ls /'
destinations: []

