# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(name)s ; %(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# File Storage
FILE_STORAGE_URL: "http://file-storage:80/files/"

# SCP
AE_TITLE: "DICOMFLOW"
AE_HOSTNAME: "storescp"
AE_PORT: 10000
AE_BLACKLISTED_IP_NETWORKS: null
AE_WHITELISTED_IP_NETWORKS: null
PYNETDICOM_LOG_LEVEL: 30
PUB_ROUTING_KEY_ERROR: "error"
PUB_ROUTING_KEY_SUCCESS: "success"
PUB_ROUTING_KEY_FAIL: "fail"
PUB_MODELS:
  - exchange: "storescp"
    exchange_type: "topic"

